# JavaScript Syntax Check
name: workflow.yml

# Workflow triggered main pushed/pulled
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
        # Workflow steps
    steps:
      # Checks out the repo code 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          
      # Installs dependencies
      - run: npm install
      # Runs the ESLint tool on all JS files in root directory
      - run: npx eslint .
      
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
